name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow pytest build
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build meson
      - name: Build libisyntax
        run: |
          meson setup build
          meson compile -C build
          cp build/libisyntax.so python_isyntax/python_isyntax/
      - name: Run tests
        run: pytest python_isyntax/tests
      - name: Build wheel
        run: python -m build --wheel --outdir dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
