name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow pytest
      - name: Run tests
        run: pytest python_isyntax/tests
      - name: Build package
        run: |
          python -m pip install build
          cd python_isyntax
          python -m build
      - name: Publish to GitHub Packages
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.GITHUB_TOKEN }}
          repository-url: "https://pypi.pkg.github.com/${{ github.repository_owner }}"
          packages-dir: python_isyntax/dist
